// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: application.sql

package db

import (
	"context"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO shen_application(name)
  VALUES ($1)
RETURNING
  id, name, active, created_at, updated_at
`

func (q *Queries) CreateApplication(ctx context.Context, name string) (ShenApplication, error) {
	row := q.db.QueryRow(ctx, createApplication, name)
	var i ShenApplication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateApplication = `-- name: DeactivateApplication :exec
UPDATE
  shen_application
SET
  active = FALSE
WHERE
  id = $1
`

func (q *Queries) DeactivateApplication(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deactivateApplication, id)
	return err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM shen_application
WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT
  id,
  name,
  active,
  created_at,
  updated_at
FROM
  shen_application
WHERE
  id = $1
LIMIT 1
`

func (q *Queries) GetApplicationByID(ctx context.Context, id int32) (ShenApplication, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i ShenApplication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationByName = `-- name: GetApplicationByName :one
SELECT
  id,
  name,
  active,
  created_at,
  updated_at
FROM
  shen_application
WHERE
  name = $1
LIMIT 1
`

func (q *Queries) GetApplicationByName(ctx context.Context, name string) (ShenApplication, error) {
	row := q.db.QueryRow(ctx, getApplicationByName, name)
	var i ShenApplication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveApplications = `-- name: ListActiveApplications :many
SELECT
  id,
  name,
  active,
  created_at,
  updated_at
FROM
  shen_application
WHERE
  active = TRUE
ORDER BY
  name
LIMIT $1 OFFSET $2
`

type ListActiveApplicationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActiveApplications(ctx context.Context, arg ListActiveApplicationsParams) ([]ShenApplication, error) {
	rows, err := q.db.Query(ctx, listActiveApplications, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenApplication
	for rows.Next() {
		var i ShenApplication
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplications = `-- name: ListApplications :many
SELECT
  id,
  name,
  active,
  created_at,
  updated_at
FROM
  shen_application
ORDER BY
  name
LIMIT $1 OFFSET $2
`

type ListApplicationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListApplications(ctx context.Context, arg ListApplicationsParams) ([]ShenApplication, error) {
	rows, err := q.db.Query(ctx, listApplications, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenApplication
	for rows.Next() {
		var i ShenApplication
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :exec
UPDATE
  shen_application
SET
  name = $2,
  active = $3
WHERE
  id = $1
`

type UpdateApplicationParams struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	Active bool   `json:"active"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) error {
	_, err := q.db.Exec(ctx, updateApplication, arg.ID, arg.Name, arg.Active)
	return err
}
