// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group.sql

package db

import (
	"context"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO shen_group(name)
  VALUES ($1)
RETURNING
  id, name, active, created_at, updated_at
`

func (q *Queries) CreateGroup(ctx context.Context, name string) (ShenGroup, error) {
	row := q.db.QueryRow(ctx, createGroup, name)
	var i ShenGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateGroup = `-- name: DeactivateGroup :exec
UPDATE
  shen_group
SET
  active = FALSE
WHERE
  id = $1
`

func (q *Queries) DeactivateGroup(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deactivateGroup, id)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM shen_group
WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT
  id,
  name,
  active,
  created_at,
  updated_at
FROM
  shen_group
WHERE
  id = $1
LIMIT 1
`

func (q *Queries) GetGroupByID(ctx context.Context, id int32) (ShenGroup, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i ShenGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT
  id,
  name,
  active,
  created_at,
  updated_at
FROM
  shen_group
WHERE
  name = $1
LIMIT 1
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (ShenGroup, error) {
	row := q.db.QueryRow(ctx, getGroupByName, name)
	var i ShenGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveGroups = `-- name: ListActiveGroups :many
SELECT
  id,
  name,
  active,
  created_at,
  updated_at
FROM
  shen_group
WHERE
  active = TRUE
ORDER BY
  name
LIMIT $1 OFFSET $2
`

type ListActiveGroupsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActiveGroups(ctx context.Context, arg ListActiveGroupsParams) ([]ShenGroup, error) {
	rows, err := q.db.Query(ctx, listActiveGroups, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenGroup
	for rows.Next() {
		var i ShenGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT
  id,
  name,
  active,
  created_at,
  updated_at
FROM
  shen_group
ORDER BY
  name
LIMIT $1 OFFSET $2
`

type ListGroupsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListGroups(ctx context.Context, arg ListGroupsParams) ([]ShenGroup, error) {
	rows, err := q.db.Query(ctx, listGroups, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenGroup
	for rows.Next() {
		var i ShenGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :exec
UPDATE
  shen_group
SET
  name = $2,
  active = $3
WHERE
  id = $1
`

type UpdateGroupParams struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	Active bool   `json:"active"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.Exec(ctx, updateGroup, arg.ID, arg.Name, arg.Active)
	return err
}
