// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission.sql

package db

import (
	"context"
)

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT
    id,
    priority,
    name,
    created_at,
    updated_at
FROM
    shen_permission
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetPermissionByID(ctx context.Context, id int32) (ShenPermission, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i ShenPermission
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPermissionByName = `-- name: GetPermissionByName :one
SELECT
    id,
    priority,
    name,
    created_at,
    updated_at
FROM
    shen_permission
WHERE
    name = $1
LIMIT 1
`

func (q *Queries) GetPermissionByName(ctx context.Context, name string) (ShenPermission, error) {
	row := q.db.QueryRow(ctx, getPermissionByName, name)
	var i ShenPermission
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT
    id,
    priority,
    name,
    created_at,
    updated_at
FROM
    shen_permission
ORDER BY
    priority
`

func (q *Queries) ListPermissions(ctx context.Context) ([]ShenPermission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenPermission
	for rows.Next() {
		var i ShenPermission
		if err := rows.Scan(
			&i.ID,
			&i.Priority,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
